name: Go Format

on:
  pull_request:
    branches: ["**"]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Check gofmt
        run: |
          UNFORMATTED=$(gofmt -l $(git ls-files '*.go'))
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files need formatting:" >&2
            echo "$UNFORMATTED" >&2
            exit 1
          fi
